---
- name: Full system upgrade
  ansible.builtin.dnf:
    name: "*"
    state: latest
    allowerasing: true
  when: dnf_upgrade
  notify: Reboot

- name: Enable EPEL Repository
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Install packages
  ansible.builtin.dnf:
    name:
      - bash-completion
      - vim
      - tmux
      - htop
      - tree
      - iperf3
      - man
      - ncurses
      - bind-utils
      - rsync

- name: Template the configs
  ansible.builtin.template:
    src: "{{ item.key }}"
    dest: "{{ item.value.path }}"
    owner: "{{ item.value.owner }}"
    mode: "0644"
  with_dict:
    "templates/.tmux.conf.j2":
      path: "/root/.tmux.conf"
      owner: root
    "templates/.bashrc.j2":
      path: "/root/.bashrc"
      owner: root

- name: Install Hetrix heartbeat monitor
  ansible.builtin.cron:
    name: "hetrixtools heartbeat monitor"
    minute: "*/5"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/bin/curl --retry 3 --retry-delay 1 -m 15 https://sm.hetrixtools.net/hb/?s={{ hetrix_token }} >/dev/null 2>&1"
  when: hetrix_token is defined
